### PR TITLE
Fixed future course start date display

### LINKED ISSUE #1676: Course Status State: Enrolled with Future Start displaying incorrect # of days to start
Tested on RC.
Set a Course state to enrolled with a future start date.
python manage.py alter_data --action=set_course_to_enrolled --username=staff --program-title=’Analog’ --course-title='100' --in-future

The underlying data is a start date of 11/24/2016 (which is 20 days from today), but
the messaging is "Course starts in 19 days".

future start date

Course_info data:
{                                                                                           
  "course_runs": [                                                                          
    {                                                                                       
      "edx_course_key": "course-v1:MITx+Analog+Learning+100+Nov_2016",                      
      "enrollment_start": "10/30/2016",                                                     
      "enrollment_end": "11/09/2016",                                                       
      "upgrade_deadline": "11/29/2016",                                                     
      "start_date": "11/24/2016",                                                           
      "end_date": "12/24/2016",                                                             
      "edx_data": {                                                                         
        "CachedEnrollment": {                                                               
          "data": {                                                                         
            "course_details": {                                                             
              "enrollment_start": "2016-10-30T20:19:52.226506",                             
              "enrollment_end": "2016-11-09T20:19:52.226506",                               
              "course_id": "course-v1:MITx+Analog+Learning+100+Nov_2016"                    
            },                                                                              
            "user": "Jared",                                                                
            "mode": "verified"                                                              
          },                                                                                
          "last_request": "12/04/2016"                                                      
        }                                                                                   
      },                                                                                    
      "id": 98                                                                              
    },                                                                                      
    {                                                                                       
      "edx_course_key": "course-v1:MITx+Analog+Learning+100+Aug_2015",                      
      "enrollment_start": "08/14/2015",                                                     
      "enrollment_end": "08/28/2015",                                                       
      "upgrade_deadline": "08/21/2015",                                                     
      "start_date": "08/14/2015",                                                           
      "end_date": "12/14/2015",                                                             
      "id": 97                                                                              
    },                                                                                      
    {                                                                                       
      "edx_course_key": "course-v1:MITx+Analog+Learning+100+Jan_2015",                      
      "enrollment_start": "01/14/2015",                                                     
      "enrollment_end": "01/28/2015",                                                       
      "upgrade_deadline": "01/21/2015",                                                     
      "start_date": "01/14/2015",                                                           
      "end_date": "05/14/2015",                                                             
      "id": 96                                                                              
    }                                                                                       
  ],                                                                                        
  "course_title": "Analog Learning 100"                                                     
}

### PR DESCRIPTION
**Pull request by gsidebo**
#### What are the relevant tickets?

Fixes #1676 

#### What's this PR do?

Makes sure that the day countdown to a future course run ignores the time of day. For example, if a course starts in 3 calendar days, but the time of day for the start date is less than the current time of day, the countdown will still show 3

#### How should this be manually tested?

You can use the `alter_data` command to set a course to be enrolled and in the future:

`alter_data --action=set_course_to_enrolled --email=YOUR_EMAIL --program-title='Analog' --course-title='100' --in-future`

After that, you can run a django shell and edit the course run's `start_date` to set the time behind/ahead of the current time. The `Course starts in X days` message on the dashboard should show the same number.

### CODE REVIEW

**Comment by noisecapella** [comment]
Is this ready for review?

File: static/js/components/dashboard/CourseAction_test.js [hunk 1]
```diff
@@ -241,14 +241,38 @@ describe('CourseAction', () => {
       course.runs.length > 0 &&
       course.runs[0].status === STATUS_WILL_ATTEND
     ));
-    let startDate = moment(now).add(10, 'days').toISOString();
-    let firstRun = alterFirstRun(course, {course_start_date: startDate});
+    let startDate = moment(now).add(10, 'days');
```
Comment (noisecapella) [inline static/js/components/dashboard/CourseAction_test.js]: This is fine, but I'm just wondering if this was a bug or just a style change

**Comment by gsidebo** [comment]
@noisecapella sorry, forgot the label. this is indeed ready for review

File: static/js/components/dashboard/CourseAction_test.js (hunk 1 above)
Comment (gsidebo) [inline static/js/components/dashboard/CourseAction_test.js]: i just made this change to match the pattern in the tests that i added below. also, it makes more sense for a variable called `startDate` to be a moment date rather than a string. there's no functional difference from this change
