### PR TITLE
Fixed profile submission to wait for a 200

### LINKED ISSUE #270: Save and continue buttons should wait for 200 from PATCH before continuing
Needs UI for any error message

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #270

#### What's this PR do?
When we add `catch` to a `Promise` without returning another rejected `Promise`, future promises are resolved with that return value. This meant that even when the API function returned the rejected promise, the action dispatcher function returned a resolved promise.

### CODE REVIEW

File: static/js/containers/ProfilePage.js [hunk 1]
```diff
@@ -40,9 +40,9 @@ class ProfilePage extends React.Component {
       dispatch(startProfileEdit());
     }
     return dispatch(validateProfile(profile, requiredFields, messages)).then(() => {
-      dispatch(saveProfile(SETTINGS.username, profile)).then(() => {
-        dispatch(clearProfileEdit());
-      });
+      return dispatch(saveProfile(SETTINGS.username, profile));
+    }).then(() => {
+      return dispatch(clearProfileEdit());
```
Comment (aliceriot) [inline static/js/containers/ProfilePage.js]: what's the reason for changing these two lines? is there a reason we can't do this?

```js
return dispatch(validateProfile(profile, requiredFields, messages)).then(() => {
  return dispatch(saveProfile(SETTINGS.username, profile)).then(() => {
    dispatch(clearProfileEdit());
  });
});
```

still trying to wrap my head around promises a little more, and understand how this change relates to the change over in #314.

File: static/js/actions/index.js [hunk 2]
```diff
@@ -137,6 +145,10 @@ export function fetchDashboard() {
     dispatch(requestDashboard());
     return api.getDashboard().
       then(dashboard => dispatch(receiveDashboardSuccess(dashboard))).
-      catch(() => dispatch(receiveDashboardFailure()));
+      catch(e => {
+        dispatch(receiveDashboardFailure());
+        // propogate exception
+        return Promise.reject(e);
+      });
```
Comment (aliceriot) [inline static/js/actions/index.js]: does `e` have error code information and so on?

**Comment by aliceriot** [comment]
really one question, back to you!

File: static/js/containers/ProfilePage.js (hunk 1 above)
Comment (noisecapella) [inline static/js/containers/ProfilePage.js]: Just a stylistic difference, I'll change it to what we're doing in #314 

Technically the `return dispatch(clearProfileEdit())` is different but we don't use the returned value anyway

File: static/js/actions/index.js (hunk 2 above)
Comment (noisecapella) [inline static/js/actions/index.js]: It depends. If a `throw` happened in either `getDashboard` or in the `then()` immediately afterward, it would have the exception. But if there's a rejected promise then `e` is just whatever the promise value happened to be. In our `fetchJSONWithCSRF` function, if we get a non-2xx status code the value would be the content of the response

Comment (aliceriot) [inline static/js/actions/index.js]: ok cool, I was just wondering if it would make sense to surface this to the user in some way - like an 'error: connection troubles' or 'error: not authorized', etc. maybe something to worry about later.

**Comment by aliceriot** [comment]
LGTM :+1: :ship: :shipit:

File: static/js/actions/index.js (hunk 2 above)
Comment (noisecapella) [inline static/js/actions/index.js]: Yeah, I think we would want to do it when we do #234
