### PR TITLE
Fixed UI for month/year field

### LINKED ISSUE #379: Profile: make date labels behave simliar to other labels
Currently on the education and employment profile forms, the date labels don't behave the same way as other labels. The labels are also located to the left of the fields instead of above them. 

Combine the mm/yyyy into one text field, with the slash. Label should behave the same as other labels, but on focus fill the field with the hint text mm/yyyy

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #379

#### What's this PR do?
Uses the month field to show the label. MM and YYYY are now hint text

#### Screenshots (if appropriate)
monthyear_error
monthyear_month_focused
monthyear_year_focused

### CODE REVIEW

File: static/js/util/profile_edit_test.js [hunk 1]
```diff
@@ -399,27 +399,29 @@ describe('Profile Editing utility functions', () => {
     it("has proper props for an invalid or missing value", () => {
       for (let dateOfBirth of ['', {}, null, undefined]) {
         that.props.profile.date_of_birth = dateOfBirth;
-        [labelField, __, monthTextField, __, yearTextField, errorSpan] = renderMonthYearField();
+        [monthTextField, __, yearTextField] = renderMonthYearField();
```
Comment (aliceriot) [inline static/js/util/profile_edit_test.js]: can we change this to:

```js
[monthTextField, , yearTextField] = renderMonthYearField();
```
and get rid of the `__` variable?

**Comment by aliceriot** [comment]
looks great! :+1:
