### PR TITLE
Correctly handle faculty without images

### LINKED ISSUE #1560: Faculty tiles fail to render due to console error
screenshot from 2016-10-25 16-53-56

### PR DESCRIPTION
**Pull request by singingwolfboy**
Fixes #1560. The faculty carousel should now be able to display faculty even if some of them don't have an image set.

#### How should this be manually tested?
Create a ProgramPage in Wagtail with one or more faculty. Make sure that at least one of these faculty members does _not_ have an image set. View the program page in the browser, and verify that all faculty show up in the faculty carousel at the bottom.

### CODE REVIEW

**Comment by pdpinch** [comment]
Just curious: if the image is missing for an instructor, do they still get a slot in the carousel?

**Comment by singingwolfboy** [comment]
Yes, they do.
screen shot 2016-11-03 at 9 57 04 am

**Comment by noisecapella** [comment]
Code looks good, can you create `FacultyTile_test.js` and write a test for this?

**Comment by singingwolfboy** [comment]
@noisecapella: I've added tests.

File: static/js/components/FacultyTile.js [hunk 1]
```diff
@@ -14,28 +14,34 @@ export default class FacultyTile extends React.Component {
...
     }
 
     return (
       <div className="faculty-tile">
-        <img src={file} alt={alt} width={width} height={height} />
+        {imgEl}
         <div className="faculty-copy">
-        <h4>{nameStr}</h4>
-        <p>{shortBio}</p>
+          <h4>{nameStr}</h4>
```
Comment (noisecapella) [inline static/js/components/FacultyTile.js]: Can you add CSS classes for this and `p` below, and then refer to the classes in the tests instead of the element tag name?

**Comment by noisecapella** [comment]
Just a nit pick, everything else looks great

File: static/js/components/FacultyTile.js (hunk 1 above)
Comment (singingwolfboy) [inline static/js/components/FacultyTile.js]: Fixed.
