### PR TITLE
Fixed browser history for profile tabs

### LINKED ISSUE #1363: In Profile Flow, the Browser Back buttons navigate to previous page, not previous tab.
Issue is browser agnostic.
Steps to Reproduce:
Create a new profile on micromasters.herokuapp.com
Enter all the required elements on the first tab of the profile flow
https://micromasters.herokuapp.com/profile/
Click on the "next" button on the bottom.
Note that in the second "tab" of the profile flow, there is a "go back" link at the bottom
of the form which navigates the user back to the first tab of the profile flow.
However, if the user clicks on the Browser's Back button, they are taken out of the
Profile flow completely.
goback button

### PR DESCRIPTION
**Pull request by rhysyngsun**
#### What are the relevant tickets?

Fixes #1363 

#### What's this PR do?

Reintroduces named urls for the personal/education/professional tabs on the profile setup.

#### Where should the reviewer start?

Take a look at `PersonalTab` (other tabs are similar) and the routes in `dashboard_routes.js`. Also look at `currentOrFirstIncompleteStep()` in `util/util.js`.

#### How should this be manually tested?

Sign up with a new account, verify you're directed to /profile/personal by default and that you're redirected there, particularly if trying to reach one of the later steps (e.g. /profile/education or /profile/professional). You shouldn't be allowed into those later steps until you've completed the personal tab.

#### Any background context you want to provide?

We previously had named urls for each of these tabs, this PR reintroduces them, but also addresses the [original issue](https://github.com/mitodl/micromasters/issues/627) for the [PR that removed them](https://github.com/mitodl/micromasters/pull/657) so we don't have a regression on that.

#### What GIF best describes this PR or how it makes you feel?

Moonwalk

### CODE REVIEW

**Comment by aliceriot** [comment]
functionality looks good! reading code now.

File: static/js/containers/ProfilePage.js [hunk 1]
```diff
@@ -2,105 +2,95 @@
...
-    default:
-      return <PersonalTab {...props} />;
+      if (profile !== undefined) {
+        const [ , step, ] = validateProfileComplete(profile);
+        // determine the ideal step we should be on
+        // this will either be the current step if all preceding steps are complete
+        // or the least complete step below the current one
+        let idealStep = currentOrFirstIncompleteStep(profileStep, step);
+        if (profileStep !== idealStep) {
+          // if learner is on a step they shouldn't be on yet, redirect them to the correct one
```
Comment (aliceriot) [inline static/js/containers/ProfilePage.js]: I don't think these comments are super necessary, you can keep them if you want though.

Comment (aliceriot) [inline static/js/containers/ProfilePage.js]: (b/c the code is pretty clear here)

File: static/js/containers/ProfilePage_test.js [hunk 2]
```diff
@@ -1,4 +1,6 @@
 /* global SETTINGS: false */
+import '../global_init';
```
Comment (aliceriot) [inline static/js/containers/ProfilePage_test.js]: whats the reason for this import?

File: static/js/containers/ProfilePage_test.js [hunk 3]
```diff
@@ -127,35 +126,31 @@ describe("ProfilePage", function() {
...
   });
 
   for (let step of profileSteps.slice(0,2)) {
     for (let filledOutValue of [true, false]) {
       it(`respects the current value (${filledOutValue}) when saving on ${step}`, () => {
-        setStep(step);
         let updatedProfile = Object.assign({}, USER_PROFILE_RESPONSE, {
           filled_out: filledOutValue,
-          education: []
+          e3ducation: []
```
Comment (aliceriot) [inline static/js/containers/ProfilePage_test.js]: typo?

File: static/js/containers/ProfilePage_test.js (hunk 2 above)
Comment (rhysyngsun) [inline static/js/containers/ProfilePage_test.js]: I swear there was a way I was running the tests where it failed without that import, but I can't reproduce it or remember exactly what  the error was. I'll remove it.

Comment (noisecapella) [inline static/js/containers/ProfilePage_test.js]: Maybe you were running the tests through your IDE? We explicitly include this file in our mocha command in `package.json`, maybe you need to edit your test configuration to do the same for your IDE

File: static/js/util/util.js [hunk 4]
```diff
@@ -180,6 +181,31 @@ export function makeProfileProgressDisplay(active: string) {
...
+  }
+
+  const currentStepIndex = R.indexOf(currentStep, PROFILE_STEP_ORDER);
+  let stepIndex = R.indexOf(validatedStep, PROFILE_STEP_ORDER);
+
+  // take the lesser of the page we're on and the least completed step
+  const idealStepIndex = Math.min(stepIndex, currentStepIndex);
+
+  return PROFILE_STEP_ORDER[idealStepIndex];
+}
```
Comment (rhysyngsun) [inline static/js/util/util.js]: Good idea, still need to manually test, but this handles the nulls and passes my unit tests:

```es6
const getStepIndices = R.map(R.indexOf(R.__, PROFILE_STEP_ORDER));
const lastStep = R.last(PROFILE_STEP_ORDER);

export const currentOrFirstIncompleteStep = R.compose(
    R.nth(R.__, PROFILE_STEP_ORDER),
    R.reduce(R.min, Infinity),
    getStepIndices,
    R.append(lastStep),
    R.reject(R.isNil),
    R.pair
);
```

File: static/js/containers/ProfilePage.js [hunk 5]
```diff
@@ -2,105 +2,95 @@
...
-    let [prev, next] = this.stepTransitions();
-    props = Object.assign({}, this.profileProps(profileInfo), {
-      prevStep: prev,
-      nextStep: next
-    });
-    let profile: Profile = props.profile;
+  renderContent(username: string, profileInfo: ProfileGetResult, profile: Profile, currentStep: ?string) {
+    if (R.isNil(profileInfo)) {
+      return '';
+    }
```
Comment (rhysyngsun) [inline static/js/containers/ProfilePage.js]: In practice, at least the first time `ProfilePage`'s render method gets hit, `profileInfo` is `undefined`.

Comment (aliceriot) [inline static/js/containers/ProfilePage.js]: Oh that makes sense, because the dashboard API response hasn't come back yet.

**Comment by rhysyngsun** [comment]
Hmm, I didn't think this was actually a coverage decrease...looking into that.

**Comment by aliceriot** [comment]
would you mind adding new commits to the PR when you update it? It makes the review a little bit easier and makes it easier to follow your progress.

**Comment by rhysyngsun** [comment]
@aliceriot gah, sorry! noticed your comment too late. I'm an obsessive rebaser/squasher.

To make up for that, here's a list of change in my last push:

- Removed extraneous `if (profile !== undefined){}` wrapping lines 40-44 here: https://github.com/mitodl/micromasters/pull/1814/files#diff-7070f6579a91d7efe615fe81a22bdafeR40
- Fixed the typo
- Refactored `currentOrFirstIncompleteStep` per your recommendations here: https://github.com/mitodl/micromasters/pull/1814/files#diff-3c2e3ec6197c815c23dad44b122f3002R184
- Removed `nextStep` / `prevStep` from `SettingsPage` since they're no longer used and it was indirectly reducing test coverage: https://github.com/mitodl/micromasters/pull/1814/files#diff-0edec7f878bf81603aeb87f756925f46R26
- Added these tests to boost `ProfilePage` test coverage back to 100%: https://github.com/mitodl/micromasters/pull/1814/files#diff-c2220af76fb0be7547e07aabb356fe9eR136
- Renamed a test constant and added another below it: https://github.com/mitodl/micromasters/pull/1814/files#diff-c2220af76fb0be7547e07aabb356fe9eR50

**Comment by aliceriot** [comment]
It's fine to rebase, just save the squash for merge-time.

**Comment by aliceriot** [comment]
I rebase every time I update my branches on github too.

File: static/js/components/PersonalTab_test.js [hunk 6]
```diff
@@ -25,6 +33,13 @@ describe("PersonalTab", () => {
     );
   };
 
+  beforeEach(() => {
+    if ( window.localStorage === undefined ) {
+      window.localStorage = localStorageMock();
+    }
+    store = configureMainTestStore(rootReducer);
```
Comment (aliceriot) [inline static/js/components/PersonalTab_test.js]: You could use an `integrationTestHelper` here to get this for free - might be worth it even if you're not going to use it's various test methods (`listenForActions` and so on).

File: static/js/containers/ProfilePage_test.js [hunk 7]
```diff
@@ -127,35 +129,59 @@ describe("ProfilePage", function() {
...
       };
-      setStep(EMPLOYMENT_STEP);
-      return renderComponent('/profile', successActions).then(dialogTest);
+      return renderComponent('/profile/professional', SUCCESS_ACTIONS).then(dialogTest);
+    });
+  });
+
+  describe('profile completeness', () => {
+    let checkStep = () => helper.store.getState().ui.profileStep;
+
```
Comment (aliceriot) [inline static/js/containers/ProfilePage_test.js]: could you get rid of this extra line here?

Comment (rhysyngsun) [inline static/js/containers/ProfilePage_test.js]: Yup will do, also just caught that `checkStep` is now defined twice in this file and is also a bit of a misnomer.

File: static/js/components/PersonalTab_test.js (hunk 6 above)
Comment (rhysyngsun) [inline static/js/components/PersonalTab_test.js]: done

File: static/js/containers/ProfilePage_test.js (hunk 7 above)
Comment (aliceriot) [inline static/js/containers/ProfilePage_test.js]: haha, good catch

File: static/js/components/ProfileProgressControls.js [hunk 8]
```diff
@@ -32,22 +37,23 @@ export default class ProfileProgressControls extends React.Component {
...
       prevButton = <button
         className="mdl-button gray-button go-back prev"
-        onClick={prevStep}>
+        onClick={this.stepBack}>
         <span>Go Back</span>
       </button>;
     }
-    if(nextStep) {
+    if (nextUrl) {
+
```
Comment (aliceriot) [inline static/js/components/ProfileProgressControls.js]: blank line

File: static/js/constants.js [hunk 9]
```diff
@@ -31,6 +32,11 @@ export const PROFILE_STEP_LABELS = new Map([
   [EDUCATION_STEP, "Education"],
   [EMPLOYMENT_STEP, "Professional"]
 ]);
```
Comment (aliceriot) [inline static/js/constants.js]: could you add a blank line here?

File: static/js/containers/App_test.js [hunk 10]
```diff
@@ -80,48 +81,49 @@ describe('App', () => {
   describe('profile completeness', () => {
     let checkStep = () => helper.store.getState().ui.profileStep;
 
-    it('redirects to /profile if profile is not complete', () => {
+
```
Comment (aliceriot) [inline static/js/containers/App_test.js]: blank line

File: static/js/containers/ProfilePage_test.js [hunk 11]
```diff
@@ -127,35 +131,56 @@ describe("ProfilePage", function() {
...
         activeDialog('employment-dialog-wrapper');
       };
-      setStep(EMPLOYMENT_STEP);
-      return renderComponent('/profile', successActions).then(dialogTest);
+      return renderComponent('/profile/professional', SUCCESS_ACTIONS).then(dialogTest);
+    });
+  });
+
+  describe('profile completeness', () => {
+
```
Comment (aliceriot) [inline static/js/containers/ProfilePage_test.js]: blank line
