### PR TITLE
Turned on dialog scrollbars

### LINKED ISSUE #320: Bug: When the viewport shrinks, the pop-up form can be obscured
Steps to reproduce:

1. Login with edX
2. Navigate to https://micromasters-ci.herokuapp.com/profile/education
3. Click + to add a degree, for example, high school
4. Shrink the browser window vertically (for example, by opening the developer console)

Expected Behavior:

Either the pop-up window shrinks and a scrollbar is added or the pop-up window doesn't stays fixed.

Actual behavior:

The pop-up window shrinks and there is no scrollbar. The user can no longer reach the save or cancel buttons.

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #320 

#### What's this PR do?
Turns on dialog scrollbars, and tweaks CSS to remove border lines from the top and bottom of dialog

#### Screenshots (if appropriate)
screenshot from 2016-05-19 18-01-34

### CODE REVIEW

File: static/js/components/EmploymentTab.js [hunk 1]
```diff
@@ -261,9 +261,11 @@ class EmploymentTab extends ProfileTab {
         <Grid className="profile-tab-grid no-border">
           <Dialog
             open={workDialogVisibility}
-            className="profile-employment-dialog"
+            className="dashboard-dialog"
             onRequestClose={this.closeWorkDialog}
-            actions={actions}>
+            actions={actions}
+            autoScrollBodyContent={true}
```
Comment (aliceriot) [inline static/js/components/EmploymentTab.js]: oh snazzy! I thought we've have to muck around with `overflow: scroll` and all that.

**Comment by aliceriot** [comment]
LGTM :+1: :fireworks: :confetti_ball: :shipit:

File: static/js/components/EmploymentTab.js (hunk 1 above)
Comment (noisecapella) [inline static/js/components/EmploymentTab.js]: Me too, but luckily I read the docs before I went too far with that
