### PR TITLE
Show grade for prior passed course runs

### LINKED ISSUE #1887: Dashboard: show passed grade for prior runs
This is an edge case since `CourseSubRow` will probably only be used to show failed course runs. If the user passed a course they should not have the ability to retake the course. But if they do (via edX maybe) we should show the passed grade for the previous course. Currently we only show the final grade for failed course runs.

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

this closes #1887 

#### What's this PR do?

This changes the `CourseSubRow` component so that it will now show the grade for a past `CourseRun` which the user passed.

#### How should this be manually tested?

There's a patch here: https://gist.github.com/aliceriot/d729233d17d33bc0567bd0897de916a7#file-mm_mock_api_12_14_16 which will set things up to test this with the data in `constants.js`. Here's how to use it:

```
curl https://gist.githubusercontent.com/aliceriot/d729233d17d33bc0567bd0897de916a7/raw/610744ad5ad3603622760492e99ed1b1946d7549/mm_mock_api_12_14_16 > mock_api.patch
git apply mock_api.patch
```

then when you visit the dashboard there should be a course in the `Master` program titled `Passed course, most recent run non-passed, older passed`, which will have two past course runs, one passed and one failed.

#### Screenshots (if appropriate)

passed_two_course_runs

### CODE REVIEW

File: static/js/components/dashboard/CourseSubRow.js [hunk 1]
```diff
@@ -124,11 +125,21 @@ export default class CourseSubRow extends React.Component {
...
+      status = 'Passed';
+    }
     return <div className="course-action">
-      { courseRun.status === STATUS_NOT_PASSED ? 'Failed' : '' }
+      { status }
     </div>;
   }
 
+  courseRunGrade = (courseRun: CourseRun) => (
+    [STATUS_NOT_PASSED, STATUS_PASSED].includes(courseRun.status) ? formatGrade(courseRun.final_grade) : ''
```
Comment (gsidebo) [inline static/js/components/dashboard/CourseSubRow.js]: can you add a helper method `isCompletedCourseRun` that performs this logic (`[STATUS_NOT_PASSED, STATUS_PASSED].includes(courseRun.status)`) and call it here and line 166?

File: static/js/components/dashboard/CourseSubRow.js [hunk 2]
```diff
@@ -124,11 +125,21 @@ export default class CourseSubRow extends React.Component {
...
     }
+    let status = '';
+    if ( courseRun.status === STATUS_NOT_PASSED ) {
+      status = 'Failed';
+    } else if ( courseRun.status === STATUS_PASSED ) {
+      status = 'Passed';
+    }
     return <div className="course-action">
-      { courseRun.status === STATUS_NOT_PASSED ? 'Failed' : '' }
+      { status }
```
Comment (gsidebo) [inline static/js/components/dashboard/CourseSubRow.js]: this method is a little hairy now (it was a little hairy before, but is somewhat more hairy with these changes). i think it's appropriate to split this up at this point. something roughly like this:

```javascript
renderAction(): React$Element<any> {
  if (courseRun.status === STATUS_OFFERED) {
    return this.renderOfferedCourseAction();
  else if (this.isCompletedCourseRun(courseRun)) {
    return this.renderGradeStatus(); // or just copy lines 128 to 136 here...
  }
  else {
    return null;
  }
}
```

**Comment by gsidebo** [comment]
@aliceriot patch isn't working, fyi: `fatal: corrupt patch at line 105`

**Comment by gsidebo** [comment]
i applied the changes by hand and the functionality looks good

**Comment by aliceriot** [comment]
hm, try this one:

```
diff --git a/static/js/constants.js b/static/js/constants.js
index aac9ccc..1d7c0b3 100644
--- a/static/js/constants.js
+++ b/static/js/constants.js
@@ -621,8 +621,12 @@ export const DASHBOARD_RESPONSE = deepFreeze([
         "prerequisites": ""
       },
     ],
-    "financial_aid_availability": false,
-    "id": 6
+    "financial_aid_availability": true,
+    "id": 6,
+    "financial_aid_user_info": {
+      "max_possible_cost": 1000,
+      "min_possible_cost": 100,
+    }
   },
 ]);
 
diff --git a/static/js/lib/api.js b/static/js/lib/api.js
index a3d4e0e..d2e921b 100644
--- a/static/js/lib/api.js
+++ b/static/js/lib/api.js
@@ -9,6 +9,12 @@ import type { CheckoutResponse } from '../flow/checkoutTypes';
 import type { Dashboard } from '../flow/dashboardTypes';
 import type { AvailableProgram, AvailablePrograms } from '../flow/enrollmentTypes';
 import type { EmailSendResponse } from '../flow/emailTypes';
+import {
+  DASHBOARD_RESPONSE,
+  PROGRAMS,
+  COURSE_PRICES_RESPONSE,
+  USER_PROGRAM_RESPONSE,
+} from '../constants';
 
 export function getCookie(name: string): string|null {
   let cookieValue = null;
@@ -151,15 +157,21 @@ export function patchUserProfile(username: string, profile: Profile): Promise<Pr
 }
 
 export function getDashboard(): Promise<Dashboard> {
-  return mockableFetchJSONWithCSRF('/api/v0/dashboard/', {}, true);
+  // return mockableFetchJSONWithCSRF('/api/v0/dashboard/', {}, true);
+  return Promise.resolve(DASHBOARD_RESPONSE);
 }
 
 export function checkout(courseId: string): Promise<CheckoutResponse> {
-  return mockableFetchJSONWithCSRF('/api/v0/checkout/', {
-    method: 'POST',
-    body: JSON.stringify({
-      course_id: courseId
-    })
+  // return mockableFetchJSONWithCSRF('/api/v0/checkout/', {
+  //   method: 'POST',
+  //   body: JSON.stringify({
+  //     course_id: courseId
+  //   })
+  // });
+  return new Promise(resolve => {
+    setTimeout(() => {
+      resolve();
+    }, 1000);
   });
 }
 
@@ -175,7 +187,8 @@ export function sendSearchResultMail(subject: string, body: string, searchReques
 }
 
 export function getPrograms(): Promise<AvailablePrograms> {
-  return mockableFetchJSONWithCSRF('/api/v0/programs/', {}, true);
+  // return mockableFetchJSONWithCSRF('/api/v0/programs/', {}, true);
+  return Promise.resolve(PROGRAMS);
 }
 
 export function addProgramEnrollment(programId: number): Promise<AvailableProgram> {
@@ -200,18 +213,22 @@ export function updateProfileImage(username: string, image: Blob, name: string):
 }
 
 export function addFinancialAid(income: number, currency: string, programId: number): Promise<*> {
-  return mockableFetchJSONWithCSRF('/api/v0/financial_aid_request/', {
-    method: 'POST',
-    body: JSON.stringify({
-      original_income: income,
-      original_currency: currency,
-      program_id: programId
-    })
+  // return mockableFetchJSONWithCSRF('/api/v0/financial_aid_request/', {
+  //   method: 'POST',
+  //   body: JSON.stringify({
+  //     original_income: income,
+  //     original_currency: currency,
+  //     program_id: programId
+  //   })
+  // });
+  return new Promise(resolve => {
+    setTimeout(resolve, 1000);
   });
 }
 
 export function getCoursePrices(): Promise<*> {
-  return mockableFetchJSONWithCSRF('/api/v0/course_prices/', {});
+  // return mockableFetchJSONWithCSRF('/api/v0/course_prices/', {});
+  return Promise.resolve(COURSE_PRICES_RESPONSE);
 }
 
 export function skipFinancialAid(programId: number): Promise<*> {
```

File: static/js/components/dashboard/CourseSubRow.js (hunk 2 above)
Comment (aliceriot) [inline static/js/components/dashboard/CourseSubRow.js]: Yeah, I think something like that makes sense.

**Comment by aliceriot** [comment]
@gsidebo comments addressed!

File: static/js/components/dashboard/CourseSubRow.js [hunk 3]
```diff
@@ -109,25 +118,42 @@ export default class CourseSubRow extends React.Component {
...
+
+  courseRunStatus = (courseRun: CourseRun) => {
+    if (courseRun.status === STATUS_NOT_PASSED ) {
+      return 'Failed';
+    } else if ( courseRun.status === STATUS_PASSED ) {
+      return 'Passed';
+    }
+  };
+
+  renderCourseRunGrade = (courseRun: CourseRun) => (
```
Comment (gsidebo) [inline static/js/components/dashboard/CourseSubRow.js]: this isn't really returning a course run _grade_. just a string indicating the status. i think this should be called `renderCourseRunStatus`. the contents of `courseRunStatus` (line 136) can probably just be cut/pasted into the body of this one

File: static/js/components/dashboard/CourseSubRow.js [hunk 4]
```diff
@@ -145,20 +171,20 @@ export default class CourseSubRow extends React.Component {
...
+            { this.courseRunGrade(courseRun) }
           </div>
         </Cell>,
         <Cell col={4} key="3">
           { this.renderAction() }
         </Cell>
       ];
-      if (courseRun.status === STATUS_NOT_PASSED) {
-        subRowClass = `${subRowClass} course-not-passed`;
+      if (courseRun.status === STATUS_PASSED || courseRun.status === STATUS_NOT_PASSED) {
```
Comment (gsidebo) [inline static/js/components/dashboard/CourseSubRow.js]: please change this to call `isCompletedCourseRun`
