### PR TITLE
Fixed high school validation error

### LINKED ISSUE #436: Bug: Can't save High School Degree
Steps to reproduce:

1. Navigate to education profile
2. Click to add a High School degree
3. Fill out the form completely. 
4. Click Save
Nothing happens

Expected Behavior: Either the form saves and the pop-up is dismissed, or a validation error is returned. 

Most likely, when the field of study was removed in #332 we neglected to remove it from the validation.

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #436 

#### What's this PR do?
Skips field of study validation for high school entries

#### How should this be manually tested?
The reviewer should be able to fill in their high school information

### CODE REVIEW

File: static/js/util/validation.js [hunk 1]
```diff
@@ -71,6 +73,10 @@ export function educationValidation(profile) {
   ];
   if ( !_.isEmpty(profile.education) ) {
     let requiredFields = handleNestedValidation(profile, nestedKeys, 'education');
+    requiredFields = requiredFields.filter(([, index, key]) =>
+      // don't require field of study for high school students
+      !(key === 'field_of_study' && _.get(profile, ['education', index, 'degree_name']) === HIGH_SCHOOL)
+    );
```
Comment (aliceriot) [inline static/js/util/validation.js]: nice! this is exactly what I was hoping this refactor (to `validation.js`) would enable, easily inserting logic for more specific validations.

**Comment by aliceriot** [comment]
:+1:
