### PR TITLE
Fixed handling of multiple validation errors for education and work history

### LINKED ISSUE #490: Only one validation error is shown in education form at a time
To reproduce, open a new education and click Save

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #490 

#### What's this PR do?
Fixes bug in `checkFieldPresence` to combine errors correctly. Currently it uses `Object.assign` which won't combine nested values correctly

#### How should this be manually tested?
Open a new education, then click save without typing anything. All fields should be marked as needing validation

### CODE REVIEW

File: static/js/util/validation.js [hunk 1]
```diff
@@ -10,12 +10,15 @@ let handleNestedValidation = (profile, keys, nestedKey) => {
...
+
+  for (let keySet of requiredFields) {
     let val = _.get(profile, keySet);
     if (_.isUndefined(val) || _.isNull(val) || val === "" ) {
-      return _.set({}, keySet,  `${messages[keySet.slice(-1)[0]]} is required`);
+      _.set(errors, keySet,  `${messages[keySet.slice(-1)[0]]} is required`);
     }
-  }));
+  }
+  return errors;
```
Comment (aliceriot) [inline static/js/util/validation.js]: Ah I see, before I had written this:

```js
Object.assign({}, ...requiredFields.map (keySet => { ... });
```

where the arrow function returns something that should look like this:

```js
{'work_history': [
  {'fieldName': 'Field Name is required'}
]}
```

so we're splatting a bunch of these objects together, but whichever one ends up being last sets the `work_history` key on the object we end up returning to just the one error. bleh, this is what happens when you get too fancy...

**Comment by aliceriot** [comment]
looks good, all the validation errors show up.

:+1:

File: static/js/util/validation.js (hunk 1 above)
Comment (noisecapella) [inline static/js/util/validation.js]: Yes, exactly
