### PR TITLE
Fixed order fulfillment race condition

### LINKED ISSUE #1242: Possible race condition with order fulfillment
Since order fulfillment happens via postback, the user may get redirected back to the dashboard before the order is fulfilled. This means they still see the pay button even though they paid. So far this has been instantaneous so we haven't seen this yet but we may encounter it after release. Ideas to fix:

 - replace the order fulfillment message with 'Order being fulfilled, may take a few minutes...' or something like that
 - Use the order fulfillment GET parameter as a message to disable payment buttons

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1242 

#### What's this PR do?
Handles the race condition by waiting and polling the dashboard API until the API shows the course as being passed

#### How should this be manually tested?
I'll set up the PR build for this, talk to me to walk you through this

#### Screenshots
screenshot from 2016-10-13 12-40-35

After 30 seconds...
screenshot from 2016-10-13 12-40-44

### CODE REVIEW

File: static/js/containers/DashboardPage.js [hunk 1]
```diff
@@ -78,23 +82,32 @@ class DashboardPage extends React.Component {
...
-        message: `You are now enrolled in ${course.title}`,
-        icon: TOAST_SUCCESS,
-      }));
-      this.context.router.push('/dashboard/');
+      if (courseRun.status === STATUS_CAN_UPGRADE || courseRun.status === STATUS_OFFERED) {
+        dispatch(setToastMessage({
+          title: 'Order is processing',
+          message: `Please refresh after a minute...`,
+        }));
+        dispatch(updateCourseStatus(courseRun.course_id, STATUS_CURRENTLY_ENROLLED));
```
Comment (aliceriot) [inline static/js/containers/DashboardPage.js]: if the payment failed will this be un-done when the user next refreshes the dashboard?

**Comment by pdpinch** [comment]
Can we get a couple of screenshots of the possible toast messages?

**Comment by noisecapella** [comment]
Tests still need fixing but otherwise this is ready for review

**Comment by noisecapella** [comment]
Tests are fixed!

File: static/js/containers/ProfilePage_test.js [hunk 2]
```diff
@@ -40,10 +43,12 @@ describe("ProfilePage", function() {
     listenForActions = helper.listenForActions.bind(helper);
     renderComponent = helper.renderComponent.bind(helper);
     patchUserProfileStub = helper.sandbox.stub(api, 'patchUserProfile');
+    clock = sinon.useFakeTimers();
   });
 
   afterEach(() => {
     helper.cleanup();
+    clock.restore();
```
Comment (aliceriot) [inline static/js/containers/ProfilePage_test.js]: what do we need the fake timer stuff in here for?

File: static/js/containers/DashboardPage_test.js [hunk 3]
```diff
@@ -101,24 +115,100 @@ describe('DashboardPage', () => {
...
+          UPDATE_COURSE_STATUS
+        ]).then(() => {
+          let millis = 35001;
+          while (millis > 0) {
+            let tick = 3001;
+            millis -= 3001;
+            clock.tick(tick);
+
+            // hacky workaround, otherwise the component doesn't seem to update like it does
+            // on the browser ¯\_(ツ)_/¯
```
Comment (aliceriot) [inline static/js/containers/DashboardPage_test.js]: lol

File: static/js/actions/index.js [hunk 4]
```diff
@@ -77,13 +85,13 @@ export const receiveCheckoutFailure = (errorInfo: APIErrorInfo): Action => ({
...
-const requestCoursePrices = createAction(REQUEST_COURSE_PRICES);
+export const requestCoursePrices = createAction(REQUEST_COURSE_PRICES);
 
 export const RECEIVE_COURSE_PRICES_SUCCESS = 'RECEIVE_COURSE_PRICES_SUCCESS';
-const receiveCoursePricesSuccess = createAction(RECEIVE_COURSE_PRICES_SUCCESS);
+export const receiveCoursePricesSuccess = createAction(RECEIVE_COURSE_PRICES_SUCCESS);
 
 export const RECEIVE_COURSE_PRICES_FAILURE = 'RECEIVE_COURSE_PRICES_FAILURE';
-const receiveCoursePricesFailure = createAction(RECEIVE_COURSE_PRICES_FAILURE);
+export const receiveCoursePricesFailure = createAction(RECEIVE_COURSE_PRICES_FAILURE);
```
Comment (noisecapella) [inline static/js/actions/index.js]: We didn't have tests for them before :)

File: static/js/containers/ProfilePage_test.js (hunk 2 above)
Comment (noisecapella) [inline static/js/containers/ProfilePage_test.js]: We don't, it can be removed since it's part of the sandbox

File: static/js/actions/index.js (hunk 4 above)
Comment (aliceriot) [inline static/js/actions/index.js]: ohhh that makes sense haha

File: static/js/containers/ProfilePage_test.js (hunk 2 above)
Comment (noisecapella) [inline static/js/containers/ProfilePage_test.js]: Oh, I misread this. This was a temporary change, I'll revert

File: static/js/containers/DashboardPage.js [hunk 5]
```diff
@@ -59,18 +69,63 @@ class DashboardPage extends React.Component {
...
     ui:                       UIState,
     documents:                DocumentsState,
+    fetchDashboard:           () => void,
   };
 
   componentDidMount() {
     this.handleOrderStatus();
+
+    this.componentMountTime = moment();
+    this.hasOrderReceiptTimeout = false;
```
Comment (noisecapella) [inline static/js/containers/DashboardPage.js]: Will do

**Comment by noisecapella** [comment]
Comments addressed, and I removed the test hack too!

**Comment by aliceriot** [comment]
cool, taking a look now!

File: static/js/reducers/order_receipt.js [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+
+export type OrderReceiptState = {
+  initialTime: string,
+  timeoutActive: boolean,
+};
+
+export const INITIAL_ORDER_RECEIPT_STATE = {
+  timeoutActive: false,
+  initialTime: moment().toISOString()
+};
```
Comment (aliceriot) [inline static/js/reducers/order_receipt.js]: oh I see it's set on page load, nvm carry on :)

File: static/js/reducers/order_receipt_test.js [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+  describe('dialog visibility', () => {
+    [true, false].forEach(bool => {
+      it(`should let you set timeoutActive to ${bool}`, () => {
+        return dispatchThen(setTimeoutActive(bool), [
+          SET_TIMEOUT_ACTIVE
+        ]).then(state => {
+          assert.equal(state.timeoutActive, bool);
+        });
+      });
+    });
```
Comment (aliceriot) [inline static/js/reducers/order_receipt_test.js]: I think you might be able to use `assertReducerResultState` from `reducers/ui_test.js` here, maybe we could move that function out into `reducers/test_utils.js` or something.

File: static/js/reducers/order_receipt.js (hunk 6 above)
Comment (noisecapella) [inline static/js/reducers/order_receipt.js]: Yeah, this isn't ideal but I think it works fine for this particular use case, where the module load and the component mount happen pretty much the same time

**Comment by noisecapella** [comment]
Comments addressed
