### PR TITLE
fix phone number issues (came up w/ Vietnamese numbers)

### LINKED ISSUE #4620: issues with phone number validation
Some users have reported that their valid phone numbers are not being accepted.

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?

closes #4620 

#### What's this PR do?

just bumps up the phone number validation lib we're using to the latest version. We were using a fairly old version, and we had some users having issues where valid phone numbers were being marked as invalid (particularly ones from Vietnam).

I also added a regression test that exposed the issue and is fixed by the dependency upgrade.

#### How should this be manually tested?

confirm that you can get past the first screen of the profile flow with a Vietnamese phone number like '+84-03-6123-4567'. Also confirm on master that you cannot do so.

### CODE REVIEW

File: static/js/lib/validation/profile_test.js [hunk 1]
```diff
@@ -385,15 +385,29 @@ describe("Profile validation functions", () => {
...
-      }
-      const errors = {
-        phone_number: "Please enter a valid phone number"
-      }
-      assert.deepEqual(personalValidation(profile), errors)
+    //
+    ;[
+      ["+84-03-6123-4567", true],
+      ["+1 222", false],
+      ["asdfasdf", false]
```
Comment (ahmed-belal) [inline static/js/lib/validation/profile_test.js:392]: It would be great if you could add a couple more test values, some US phone numbers as well as the Vietnamese one you've already included. Doesn't add much as far as functionality is concerned, just being verbose with the testing.

**Comment by ahmed-belal** [comment]
FYI you can most probably fix the python build failures by pinning `isort==4.3.21` in `test_requirements.txt`, it's a known issue.

File: static/js/lib/validation/profile_test.js (hunk 1 above)
Comment (aliceriot) [reply static/js/lib/validation/profile_test.js:392]: sure, I'll add a few more - I didn't add too many other than a case that exposed the issue because the external library *should* be tested...

**Comment by aliceriot** [comment]
@ahmed-belal I added a few more test cases and added the fix you suggested for the python build

**Comment by ahmed-belal** [comment]
Yeah feel free to merge
