### PR TITLE
Fixed bug: default profile image

### LINKED ISSUE #168: Display a default image if failed to get profile image from edx
This will eventually be addressed during enrollment/profile set up. The user will be required to upload a profile image.

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #168 
#### What's this PR do?
Move default image to react component. Check if profile image from edx exists, otherwise show default.

### CODE REVIEW

File: static/js/components/Dashboard.js [hunk 1]
```diff
@@ -7,10 +7,16 @@ class Dashboard extends React.Component {
 
   render() {
     const { courseList, profile, dashboard } = this.props;
+    var imageUrl = (SETTINGS.edx_base_url + '/static/images/profiles/default_120.png').
```
Comment (noisecapella) [inline static/js/components/Dashboard.js]: Can you use `let` here instead of `var`?

**Comment by noisecapella** [comment]
Solution looks good to me. Feel free to merge after fixing linting errors :+1:
