### PR TITLE
Fixed lifecycle handling of DashboardPage to reload cleared items

### LINKED ISSUE #2878: Error when clicking back button on order summary page
screenshot from 2017-03-15 14-32-48

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #2878 

#### What's this PR do?
Fixes lifecycle handling in DashboardPage so the back button will work as expected

#### How should this be manually tested?
Click 'Pay now' and it should direct you to the order summary page. Press the back button and you should be back at the dashboard without an error.

### CODE REVIEW

File: static/js/dashboard_routes.js [hunk 1]
```diff
@@ -13,6 +13,7 @@ import Learner from './components/Learner';
 import OrderSummaryPage from './containers/OrderSummaryPage';
 
 const errorLoading = error => {
+  console.trace(error);
```
Comment (noisecapella) [inline static/js/dashboard_routes.js]: This is intentional, it shows a better stack trace of the error in Chrome

Comment (aliceriot) [inline static/js/dashboard_routes.js]: 💯
