### PR TITLE
Fixed # of Courses Passed facet disappearing (#3095)

### LINKED ISSUE #3095: Fix histogram and range facets in UI
We have a few UI issues with the histogram and range facets on the learner's search page

**1) When a range is selected on a histogram that yields no results, and a course filter is applied, the selected course filter remains in the facet** 

ss 2017-04-20 at 14 04 59

~~**2) The '# of courses passed' selected filter title is missing**~~

ss 2017-04-20 at 14 05 46

**3) When a range is applied for '# of courses passed', and any course filter is also applied, the '# of courses passed' facet disappears while the filter remains**

ss 2017-04-20 at 14 05 54

### PR DESCRIPTION
**Pull request by rhysyngsun**
#### What are the relevant tickets?
Fixes #3095

#### What's this PR do?
Adds the number of courses to the `/programs` api so that the learner search can set a proper maximum range value, rather than depending on the seemingly flaky value in the first hit (which we could be nonexistent if zero results).

#### How should this be manually tested?
- Adjust the bounds of the '# of courses passed' range filter (I set it to 2-3)
- Select any one of the course title filters (I chose 'Digital Learning 100')
- Verify the range slider for '# of courses passed' is still present

### CODE REVIEW

**Comment by noisecapella** [comment]
It looks like `currentProgramEnrollment` will keep the old data even if the programs are refreshed. Is there a way to force a refresh of `localStorage` for this PR?

**Comment by rhysyngsun** [comment]
I'd have to add some code that detects the structural difference between what's in `localStorage` vs. what came back from the API, but it's doable, if ugly.

**Comment by noisecapella** [comment]
I think it's necessary because most people will only be looking at one program so they won't have the opportunity to refresh their localStorage. We could just check if `total_courses` exists, set it to null, then proceed as before

File: static/js/components/LearnerSearch.js [hunk 1]
```diff
@@ -135,7 +135,8 @@ export default class LearnerSearch extends SearchkitComponent {
   }
 
   getNumberOfCoursesInProgram = (): number => {
-    return R.pathOr(0, ['hits', 'hits', 0, '_source', 'program', 'total_courses'], this.getResults());
+    const { currentProgramEnrollment } = this.props;
```
Comment (noisecapella) [inline static/js/components/LearnerSearch.js]: Can you add a test that the facet range has the right value?
