### PR TITLE
Fix course coupon program messages

### LINKED ISSUE #3263: Incorrect coupon message for course-level coupon
The program-level message should show that all courses cost $1000 each, but it's using the $50 of the fixed price coupon, which is incorrect since that coupon is on the course level

screenshot from 2017-06-01 11-47-20

### LINKED ISSUE #3342: Fixed value coupons show incorrect value in messaging

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #3263 

#### What's this PR do?
Fixes coupon course message bugs

#### How should this be manually tested?
Run `./scripts/test/run_snapshot_dashboard_states.sh --match coupon` on `master` and this branch, and compare the output. The program messages should be correct in the branch for this PR

### CODE REVIEW

File: static/js/containers/OrderSummaryPage.js [hunk 1]
```diff
@@ -112,24 +112,33 @@ class OrderSummaryPage extends React.Component {
...
     if (prices.data) {
       coursePrice = prices.data.find(coursePrice => coursePrice.program_id === currentProgramEnrollment.id);
     }
 
-    if (course && courseRun && coursePrice) {
-      const [coupon, calculatedPrice] = calculatePrice(courseRun.id, course.id, coursePrice, coupons.coupons);
-      let discount = null;
-      if (calculatedPrice !== null && calculatedPrice !== undefined) {
-        discount = coursePrice.price - calculatedPrice;
+    if (program && course && courseRun && coursePrice && prices.data) {
```
Comment (rhysyngsun) [inline static/js/containers/OrderSummaryPage.js]: Could move line 121 into this section since you're checking for `prices.data` twice and it's not used outside this.

File: static/js/components/dashboard/CourseRow.js [hunk 2]
```diff
@@ -62,30 +54,41 @@ export default class CourseRow extends React.Component {
...
   }
 
+  getCourseCoupon = (): ?Coupon => {
+    const {
+      couponPrices,
+      course,
+    } = this.props;
+
+    const couponPrice = couponPrices.pricesInclCouponByCourse.get(course.id);
+    if (!couponPrice) {
```
Comment (rhysyngsun) [inline static/js/components/dashboard/CourseRow.js]: Any reason not to use `return couponPrice ? couponPrice.coupon : undefined`?

File: static/js/lib/coupon.js [hunk 3]
```diff
@@ -29,34 +30,81 @@ function makeProgramIdLookup<T: HasProgramId>(arr: Array<T>): Map<number, T> {
...
+
   for (const program of programs) {
+    let priceObj = priceLookup.get(program.id);
+    if (!priceObj) {
+      // Shouldn't get here, we should only be calling this function
+      // if we retrieved all the values from the API already
+      throw 'Unable to find program to get the price';
+    }
+    let originalPrice = priceObj.price;
+    // Currently only one coupon per program is allowed, even if that program only affects one course
```
Comment (noisecapella) [inline static/js/lib/coupon.js]: yes

File: static/js/containers/OrderSummaryPage.js (hunk 1 above)
Comment (noisecapella) [inline static/js/containers/OrderSummaryPage.js]: Line 121 defines `coursePrice` which is used in this expression

Comment (rhysyngsun) [inline static/js/containers/OrderSummaryPage.js]: gah, right...

File: static/js/lib/coupon.js [hunk 4]
```diff
@@ -29,34 +30,81 @@ function makeProgramIdLookup<T: HasProgramId>(arr: Array<T>): Map<number, T> {
...
+    let adjustedPrice = originalPrice;
+    if (coupon) {
+      adjustedPrice = calculateDiscount(originalPrice, coupon.amount_type, coupon.amount);
+    }
+
+    let priceExclCouponByProgram = {
+      price: originalPrice,
+      coupon: null,
+    };
+    let isProgramCoupon = (
```
Comment (noisecapella) [inline static/js/lib/coupon.js]: I'm not sure about that link, we don't have a `obj` to use with `isProgramCoupon`
