### PR TITLE
Search: Fix SelectedFilters titles

### LINKED ISSUE #2964: Search: Fix selected filter text on search page
ss 2017-03-27 at 11 50 34

Our selected filter component currently shows the ES field name in the text (eg: `courses:`, `program.semester_enrollments.semester:`). This information is irrelevant to our users, and it's jarring to look at. We should remove that text. 

This most likely happened as a result of upgrading searchkit.

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #2964

#### What's this PR do?
Change the selected filter tag to display the filter name instead of the `field` prop.
Create SelectedFilter component to override the `SelectedFilters` component.
#### How should this be manually tested?
Go to learners search and select filters. Check the labels:
screen shot 2017-04-04 at 2 27 47 pm

### CODE REVIEW

**Comment by pdpinch** [comment]
This reminds me that it would be really nice if we could display the full name of the country, instead of the abbreviation (i.e. "Canada" instead of "CA"). Let me know if it should be a separate issue.

**Comment by annagav** [comment]
Added new commit to display full names for countries and states:

screen shot 2017-04-04 at 5 23 59 pm

File: static/js/components/search/ModifiedSelectedFilter.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+    } else if (filterName in this.countryNameTranslations) {
+      filterName = this.countryNameTranslations[filterName];
+    }
+    return <div className={bemBlocks.option()
+    .mix(bemBlocks.container("item"))
+    .mix(`selected-filter--${this.props.filterId}`)()}>
+      <div className={this.props.bemBlocks.option("name")}>{filterName}: {filterValue}</div>
+      <div className={this.props.bemBlocks.option("remove-action")} onClick={removeFilter}>x</div>
+    </div>;
+  }
```
Comment (gsidebo) [inline static/js/components/search/ModifiedSelectedFilter.js]: I played around with getting rid of the need for custom rendering code, but due to the extensive usage of `this.props` in searchkit I couldn't see a clean way to do it. I did make this `render` method a little more concise in the process, though. What do you think of this?

```javascript
render() {
    let {
      labelKey, 
      labelValue, 
      removeFilter, 
      bemBlocks, 
      filterId
    } = this.props;

    if (labelKey in FILTER_NAMES) {
      labelKey = FILTER_NAMES[labelKey];
    } else if (labelKey in this.countryNameTranslations) {
      labelKey = this.countryNameTranslations[labelKey];
    }
    if (labelValue in this.countryNameTranslations) {
      labelValue = this.countryNameTranslations[labelValue];
    }

    return (
      <div className={
        bemBlocks.option()
        .mix(bemBlocks.container("item"))
        .mix(`selected-filter--${filterId}`)()
      }>
        <div className={bemBlocks.option("name")}>{labelKey}: {labelValue}</div>
        <div className={bemBlocks.option("remove-action")} onClick={removeFilter}>x</div>
      </div>
    );
  }
```

File: static/js/constants.js [hunk 2]
```diff
@@ -24,6 +24,16 @@ export const EDUCATION_LEVELS = [
   {value: DOCTORATE, label: "Doctorate"}
 ];
 
+export const FILTER_NAMES = {
```
Comment (gsidebo) [inline static/js/constants.js]: this name could be more helpful. `SEARCH_FILTER_ID_LABEL_MAP`, maybe?

Comment (annagav) [inline static/js/constants.js]: How about this one: `SEARCH_FACET_FIELD_TITLE_MAP`?

Comment (gsidebo) [inline static/js/constants.js]: maybe `SEARCH_FACET_FIELD_LABEL_MAP` since the value is being used more as a 'label' than a title. either one would work. i'll leave it to you

Comment (annagav) [inline static/js/constants.js]: That's true. The reason for 'title' is that searchkit uses the title prop of the component for the title of the facet as well as the label for the selected filter. Also, I think it makes it clear that the title of the facet is used to label the selected filter.

**Comment by gsidebo** [comment]
@annagav once that variable name is changed, this is good to go. i'm happy with my suggestion or yours.
