### PR TITLE
Fixed console warning for faculty carousel

### LINKED ISSUE #1322: Console error when faculty carousel contains zero items
I think we just need to check if the div exists before connecting it with React

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1322

#### What's this PR do?
Adds a check to make sure the faculty carousel div exists before populating it

### CODE REVIEW

File: static/js/faculty_carousel.js [hunk 1]
```diff
@@ -5,7 +5,9 @@ import React from 'react';
...
-ReactDOM.render(
-  <FacultyCarousel faculty={SETTINGS.faculty} />,
-  carouselDiv
-);
+if (carouselDiv !== null) {
+  ReactDOM.render(
+    <FacultyCarousel faculty={SETTINGS.faculty}/>,
+    carouselDiv
+  );
+}
```
Comment (aliceriot) [inline static/js/faculty_carousel.js]: OK so looking at `cms/templates/cms/program_page.html` we'll have `#faculty-carousel` if there are faculty to show, and otherwise we won't.

I was worried that the error was because of a race condition, but I see that's not a concern.
