### PR TITLE
Fixed Order Summary text

### LINKED ISSUE #2922: copy error on OrderSummary
uhhh

I don't think "Clicking below with link outside of the MIT MicroMasters app to an external website" is what we want here.

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #2922

#### What's this PR do?
Update the text on the Order Summary page.

### CODE REVIEW

File: static/js/components/OrderSummary.js [hunk 1]
```diff
@@ -38,9 +38,8 @@ class OrderSummary extends React.Component {
     let text;
     let price = (finalPrice !== undefined && finalPrice !== null) ? finalPrice : coursePrice.price;
     if (price > 0) {
-      text = "Clicking below with link outside of the MIT MicroMasters app" +
-        " to an external website, where you will be able to complete the transaction by" +
-        " paying with a credit card.";
+      text = "Clicking Continue will link to a website outside of the MicroMasters app, where " +
+        "you will be able to complete the transaction, by paying with a credit card.";
```
Comment (aliceriot) [inline static/js/components/OrderSummary.js]: @roberthouse54 how sure are we of this wording? I'm just thinking that it sounds a bit strange, to my ear something like

"Clicking continue will take you to an external website, where you can complete the transaction with a credit or debit card."

sounds a lot more natural. thoughts?

Comment (roberthouse54) [inline static/js/components/OrderSummary.js]: That sounds good to me, thanks. Let's use that text.
