### PR TITLE
Fixed ES search result email bug

### LINKED ISSUE #2513: welcome email to all learners fails with `RequestError: TransportError`
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/214710346/

```
RequestError: TransportError(400, 'search_phase_execution_exception', 'Expected [FIELD_NAME] under a [START_OBJECT], but got a [START_OBJECT] in [courses]')
(17 additional frame(s) were not displayed)
...
  File "rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "mail/views.py", line 49, in post
    filter_on_email_optin=True
  File "search/api.py", line 107, in prepare_and_execute_search
    return search_func(search_obj)
  File "search/api.py", line 131, in get_all_query_matching_emails
    search_results = execute_search(search_obj[from_index: to_index])
  File "search/api.py", line 29, in execute_search
    return search_obj.execute()

RequestError: TransportError(400, 'search_phase_execution_exception', 'Expected [FIELD_NAME] under a [START_OBJECT], but got a [START_OBJECT] in [courses]')
```

### PR DESCRIPTION
**Pull request by gsidebo**
#### What are the relevant tickets?

Fixes #2513 

#### What's this PR do?

Fixes the bug we were experiencing with sending an email to users that match a search query

#### How should this be manually tested?

Send a search result email from `/learners`, and without reloading the page, change the filters several times and attempt additional search result emails with that new search result set. Confirm that you're getting the expected recipients in the body of the emails you receive

### CODE REVIEW

File: static/js/containers/LearnerSearchPage.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ class LearnerSearchPage extends React.Component {
       startEmailEdit(
         {
           type: SEARCH_EMAIL_TYPE,
-          params: {query: searchkit.query.query},
+          params: {searchkit: searchkit},
```
Comment (noisecapella) [inline static/js/containers/LearnerSearchPage.js]: I'm not sure putting `SearchkitManager` into the redux store is a good idea. Why not just pass `searchkit` when `closeEmailComposerAndSend` is called?

**Comment by giocalitri** [comment]
@noisecapella @gsidebo 
We are going to merge this as is and work on the proper fix separately
👍
