### PR TITLE
Fixed error in year validation logic

### LINKED ISSUE #1405: Birthdate year validation on the Profile Page is incorrect
A user can enter a value for their date of birth year ranging from 1800-2100.
Steps to reproduce:
Log onto MicroMasters.
Create a new edX profile.
On the first profile page, tab down (or mouse) to the Date of Birth Field.
For the Year value if a user enters "1111" the value changes to "1800"
(or you can manually enter 1800).
Similarly, a user can enter a value greater than 2017 all the way up 2100.
(or you can enter "5555" which reverts to "2100")

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

closes #1405 

#### What's this PR do?

this fixes the year validation for the profile. basically, the range of allowed years `n` now looks like `x - 120 <= n <= x` where `x` is the current year. when `x = 2016` the range is `1896 - 2016`.

#### Where should the reviewer start?

look over the logic and test changes.

#### How should this be manually tested?

go to `/learner` and open the basic info dialog. edit your birthday. you should only be able to enter years in the range above. years greater than or less than the bounds should be corrected to the closest bound (so that `1700 -> 1896`, and `2250 -> 2016`, for instance).

### CODE REVIEW

File: static/js/util/profile_edit_test.js [hunk 1]
```diff
@@ -268,21 +272,21 @@ describe('Profile Editing utility functions', () => {
       that.props.profile.date_of_birth = "1917-11-07";
       rerender(false);
       yearTextField.props.onChange({target: {value: "1233"}});
```
Comment (gsidebo) [inline static/js/util/profile_edit_test.js]: can you set a `futureYear` and `tooFarInPastYear` (et al) variable near `currentYear` and `cutoff` and replace the hardcoded values (eg: "1233", "2077") with those?

File: static/js/util/validation.js [hunk 2]
```diff
@@ -294,14 +294,16 @@ export function validateYear(input: string|number|null): Maybe<number> {
   if (year === undefined) {
     return Nothing();
   }
-  if ( year < 1800 ) {
+  let now = moment().year();
+  let cutoff = now - 120;
```
Comment (gsidebo) [inline static/js/util/validation.js]: can you put the `120` value into constants.js and refer to it here and in the unit tests?

File: static/js/util/validation_test.js [hunk 3]
```diff
@@ -385,15 +385,17 @@ describe('Profile validation functions', () => {
...
 
-    it('returns 2100 for years >= 2100', () => {
-      assertMaybeEquality(Just(2100), validateYear("2100"));
-      assertMaybeEquality(Just(2100), validateYear("2300"));
-      assertMaybeEquality(Just(2100), validateYear("52300"));
+    it('returns a maximum of the current year', () => {
+      let now = moment().year();
+      assertMaybeEquality(Just(now), validateYear("2100"));
+      assertMaybeEquality(Just(now), validateYear("2300"));
+      assertMaybeEquality(Just(now), validateYear("52300"));
```
Comment (gsidebo) [inline static/js/util/validation_test.js]: these are redundant. i think this assertion alone would do the trick

`assertMaybeEquality(Just(now), moment().add(3, "years").year());`

Comment (aliceriot) [inline static/js/util/validation_test.js]: oh yea, I was just blindly fixing the existing tests there, haha

**Comment by aliceriot** [comment]
@gsidebo comments addressed

**Comment by gsidebo** [comment]
looks great! 👍
