### PR TITLE
Moved dashboard API call to DashboardPage

### LINKED ISSUE #1655: Long delay in loading programs in profile form
Steps to reproduce:

1. On an account without a profile, load the profile form

## Expected Behavior

When the form loads and becomes interactive, the programs select list has two (or more) options. 

## Actual Behavior

When the form loads and the programs select is interactive, there are no options available. 

It takes a few more seconds after the form loads for the programs drop down to be populated. Since it's the first field in the form, users are confused why there are no choices from the drop-down.

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1655

#### What's this PR do?
Delays loading the dashboard API until the user looks at the dashboard page. The user will load the dashboard API when they click next and enroll in a program, but this shouldn't block anything on their end.

#### How should this be manually tested?
Load `/profile` and verify that no request to `/api/v0/dashboard/` is loaded and that the user still sees programs they can enroll in.

Also, go to `/settings` and refresh the browser. Verify that `/api/v0/dashboard/` is not loaded. Then click the logo on the upper left to direct you to the dashboard. Verify that the dashboard loaded properly.

### CODE REVIEW

File: static/js/containers/DashboardPage.js [hunk 1]
```diff
@@ -126,6 +135,26 @@ class DashboardPage extends React.Component {
...
 
+  updateRequirements = () => {
+    this.fetchDashboard();
+    this.fetchCoursePrices();
+    this.handleOrderStatus();
+  };
+
+  fetchDashboard() {
+    const { dashboard, dispatch } = this.props;
+    if (dashboard.fetchStatus === undefined) {
```
Comment (noisecapella) [inline static/js/containers/DashboardPage.js]: It's not possible for globals to be replaced in that matter, only locals: http://www.2ality.com/2013/04/check-undefined.html

Comment (noisecapella) [inline static/js/containers/DashboardPage.js]: TIL too, I was going to argue for it for stylistic reasons and then I found evidence to support my preference :)

Comment (aliceriot) [inline static/js/containers/DashboardPage.js]: As far as I can tell this is exactly the check that `_.isUndefined` makes anyhow: https://github.com/lodash/lodash/blob/master/lodash.js#L12197

File: static/js/containers/App_test.js [hunk 2]
```diff
@@ -38,29 +41,37 @@ import IntegrationTestHelper from '../util/integration_test_helper';
...
+    editProfileActions = successActions.concat([
       START_PROFILE_EDIT,
       START_PROFILE_EDIT,
       UPDATE_PROFILE_VALIDATION,
       SET_PROFILE_STEP,
-    ];
+    ]);
+    redirectActions = successActions.concat([
+      START_PROFILE_EDIT,
+    ]);
```
Comment (gsidebo) [inline static/js/containers/App_test.js]: looks like you're assigning expected actions in the `describe` handler in some test files, and inside the `beforeEach` handler in others. it doesn't look like you're actually changing these lists anywhere - when you need to add to the list, you are setting a different variable, which i think is the right approach. can we make this consistent?

File: static/js/components/ErrorMessage_test.js [hunk 3]
```diff
@@ -111,10 +108,32 @@ describe("ErrorMessage", () => {
...
+      const dashboardSuccessActions = [
+        REQUEST_DASHBOARD,
+        RECEIVE_DASHBOARD_SUCCESS,
+        REQUEST_COURSE_PRICES,
+        RECEIVE_COURSE_PRICES_SUCCESS,
+        REQUEST_GET_USER_PROFILE,
+        RECEIVE_GET_USER_PROFILE_SUCCESS,
+        REQUEST_GET_PROGRAM_ENROLLMENTS,
+        RECEIVE_GET_PROGRAM_ENROLLMENTS_SUCCESS,
+      ];
```
Comment (gsidebo) [inline static/js/components/ErrorMessage_test.js]: this is defined in 3 different places. can you just defined this and export it in `DashboardPage_test.js` or something like that?

**Comment by gsidebo** [comment]
functionality looks great!

**Comment by noisecapella** [comment]
Comments addressed
