### PR TITLE
Remove email info from personal profile

### LINKED ISSUE #1494: Remove email & icon from the "view profile" page in Dashboard
When a user views their own profile (i.e. goes to the "view profile" page in Dashboard), we are displaying an envelope icon & email address in the top card.  Per discussion w/ @pdpinch, please remove both.

Steps to Reproduce:
Log onto MicroMasters
Complete a profile.
On Dashboard page, select "view profile" from the dropdown in the  header.
profile email

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #1494
#### What's this PR do?

If the user is viewing his own profile, remove the email icon and information.

### CODE REVIEW

**Comment by aliceriot** [comment]
functionality looks good! looking at code now.

File: static/js/components/UserInfoCard.js [hunk 1]
```diff
@@ -21,6 +22,13 @@ export default class UserInfoCard extends React.Component {
 
   render() {
     const { profile, toggleShowPersonalDialog } = this.props;
+    let emailInfo =  <div>
+      <Icon name="email" className="email-icon" />
+      <span className="profile-email">{profile.email}</span>
+    </div>;
+    if(SETTINGS.user !== undefined && SETTINGS.user.username === profile.username){
+      emailInfo = "";
+    }
```
Comment (aliceriot) [inline static/js/components/UserInfoCard.js]: Amir just implemented a function called `isProfileOfLoggedInUser` in `util/util.js` which you could use here - it might be a little nicer if you pull the email info out into a helper method, and then below in the JSX you could do:

```js
{ isProfileOfLoggedInUser(profile) ? null : this.emailInfo() }
```

thoughts?

**Comment by annagav** [comment]
@aliceriot, thanks for the suggestion! I am using Amir's function now...

**Comment by annagav** [comment]
@aliceriot, I added some tests.

**Comment by aliceriot** [comment]
looks like there's a merge conflict too. taking a look at the tests now!

File: static/js/components/UserInfoCard_test.js [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+    SETTINGS.user.username = "My user";
+    let chip = renderInfoCard(clone);
+    assert.equal(chip.find(".profile-email").text(), clone.email);
+  });
+
+  it('should not show email if its personal card', () => {
+    let chip = renderInfoCard(clone);
+    assert(chip.find(".profile-email").isEmpty(), 'email is shown');
+  });
+});
```
Comment (aliceriot) [inline static/js/components/UserInfoCard_test.js]: Could you re-write the test descriptions to be gender-neutral and to use the user-based language we usually use? Something like `'should show email if the user is viewing their own profile'`, etc.

**Comment by annagav** [comment]
@aliceriot I resolved the conflict. Had modify Amir's tests a bit.

**Comment by aliceriot** [comment]
looks like there are some linting and flow errors, but otherwise this is looking good!

**Comment by annagav** [comment]
@aliceriot the tests are finally passing! Is it good to merge?

**Comment by aliceriot** [comment]
taking a look now!
